export const countries = [
  { name: 'India', dial_code: '+91', code: 'in' },
  { name: 'United States', dial_code: '+1', code: 'us' },
  { name: 'United Kingdom', dial_code: '+44', code: 'gb' },
  { name: 'China', dial_code: '+86', code: 'cn' },
  { name: 'Japan', dial_code: '+81', code: 'jp' },
  { name: 'Germany', dial_code: '+49', code: 'de' },
  { name: 'France', dial_code: '+33', code: 'fr' },
  { name: 'Australia', dial_code: '+61', code: 'au' },
  { name: 'Canada', dial_code: '+1', code: 'ca' },
  { name: 'Brazil', dial_code: '+55', code: 'br' },
  { name: 'Russia', dial_code: '+7', code: 'ru' },
  { name: 'Pakistan', dial_code: '+92', code: 'pk' },
  { name: 'Bangladesh', dial_code: '+880', code: 'bd' },
  { name: 'Nepal', dial_code: '+977', code: 'np' },
  { name: 'Sri Lanka', dial_code: '+94', code: 'lk' },
  { name: 'South Africa', dial_code: '+27', code: 'za' },
  { name: 'Nigeria', dial_code: '+234', code: 'ng' },
  { name: 'Indonesia', dial_code: '+62', code: 'id' },
  { name: 'Mexico', dial_code: '+52', code: 'mx' },
  { name: 'Malaysia', dial_code: '+60', code: 'my' },
];
